/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u07788816108
 */
public class JDlgMcbUsuario extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMcbUsuario
     */
    public JDlgMcbUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        habilitar(false);
    }

        public void habilitar(boolean valor) {
        jTxtNomeBataglin.setEnabled(valor);
        jFmtCPFBataglin.setEnabled(valor);
        jTxtApelidoBataglin.setEnabled(valor);
        jFmtDataBataglin.setEnabled(valor);
        jChbAtivoBataglin1.setEnabled(valor);
        jTxtCodigoBataglin.setEnabled(valor);
        jPwfSenhaBataglin.setEnabled(valor);
        jCmoNivelBataglin.setEnabled(valor);
        jBtnCancelarBataglin.setEnabled(valor);
        jBtnConfirmarBataglin.setEnabled(valor);
        jBtnPesquisarBataglin.setEnabled(!valor);
        jBtnincluirBataglin.setEnabled(!valor);
        jBtnAlterarBataglin.setEnabled(!valor);
        jBtnExcluirBataglin.setEnabled(!valor);
        }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLblCodigoBataglin = new javax.swing.JLabel();
        JLblNomeBataglin = new javax.swing.JLabel();
        JLblApelidoBataglin = new javax.swing.JLabel();
        JLblCPFBataglin = new javax.swing.JLabel();
        JLblDataNascBataglin = new javax.swing.JLabel();
        JLblNivelBataglin = new javax.swing.JLabel();
        JLblSenhaBataglin = new javax.swing.JLabel();
        jBtnincluirBataglin = new javax.swing.JButton();
        jBtnExcluirBataglin = new javax.swing.JButton();
        jBtnAlterarBataglin = new javax.swing.JButton();
        jBtnCancelarBataglin = new javax.swing.JButton();
        jBtnConfirmarBataglin = new javax.swing.JButton();
        jBtnPesquisarBataglin = new javax.swing.JButton();
        jCmoNivelBataglin = new javax.swing.JComboBox<>();
        jFmtDataBataglin = new javax.swing.JFormattedTextField();
        jFmtCPFBataglin = new javax.swing.JFormattedTextField();
        jPwfSenhaBataglin = new javax.swing.JPasswordField();
        jTxtCodigoBataglin = new javax.swing.JTextField();
        jTxtNomeBataglin = new javax.swing.JTextField();
        jTxtApelidoBataglin = new javax.swing.JTextField();
        jChbAtivoBataglin1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLblCodigoBataglin.setText("Código");

        JLblNomeBataglin.setText("Nome");

        JLblApelidoBataglin.setText("Apelido");

        JLblCPFBataglin.setText("CPF");

        JLblDataNascBataglin.setText("Data de nascimento");

        JLblNivelBataglin.setText("Nivel");

        JLblSenhaBataglin.setText("Senha");

        jBtnincluirBataglin.setBackground(new java.awt.Color(168, 245, 252));
        jBtnincluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnincluirBataglin.setText("Incluir");
        jBtnincluirBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnincluirBataglinActionPerformed(evt);
            }
        });

        jBtnExcluirBataglin.setBackground(new java.awt.Color(255, 102, 102));
        jBtnExcluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluirBataglin.setText("Excluir");
        jBtnExcluirBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirBataglinActionPerformed(evt);
            }
        });

        jBtnAlterarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterarBataglin.setText("Alterar");
        jBtnAlterarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarBataglinActionPerformed(evt);
            }
        });

        jBtnCancelarBataglin.setBackground(new java.awt.Color(153, 204, 255));
        jBtnCancelarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelarBataglin.setText("Cancelar");
        jBtnCancelarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarBataglinActionPerformed(evt);
            }
        });

        jBtnConfirmarBataglin.setBackground(new java.awt.Color(0, 153, 51));
        jBtnConfirmarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmarBataglin.setText("Confirmar");
        jBtnConfirmarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarBataglinActionPerformed(evt);
            }
        });

        jBtnPesquisarBataglin.setBackground(new java.awt.Color(51, 153, 255));
        jBtnPesquisarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisarBataglin.setText("Pesquisar");
        jBtnPesquisarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarBataglinActionPerformed(evt);
            }
        });

        jCmoNivelBataglin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jChbAtivoBataglin1.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLblCodigoBataglin)
                            .addComponent(JLblApelidoBataglin)
                            .addComponent(JLblSenhaBataglin)
                            .addComponent(JLblDataNascBataglin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtApelidoBataglin)
                            .addComponent(jTxtCodigoBataglin)
                            .addComponent(jPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataBataglin, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtNomeBataglin)
                                .addGap(224, 224, 224))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblNomeBataglin)
                                    .addComponent(JLblNivelBataglin)
                                    .addComponent(JLblCPFBataglin)
                                    .addComponent(jFmtCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCmoNivelBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jChbAtivoBataglin1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnincluirBataglin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluirBataglin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterarBataglin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelarBataglin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmarBataglin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisarBataglin)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblCodigoBataglin)
                    .addComponent(JLblNomeBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblApelidoBataglin)
                    .addComponent(JLblCPFBataglin))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApelidoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblDataNascBataglin)
                    .addComponent(JLblNivelBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmoNivelBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtDataBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(JLblSenhaBataglin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivoBataglin1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnincluirBataglin)
                    .addComponent(jBtnExcluirBataglin)
                    .addComponent(jBtnAlterarBataglin)
                    .addComponent(jBtnCancelarBataglin)
                    .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisarBataglin))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExcluirBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirBataglinActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(null, "Tem certeza que deseja continuar? Essa ação não pode ser desfeita",
"Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnExcluirBataglinActionPerformed

    private void jBtnincluirBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnincluirBataglinActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnincluirBataglinActionPerformed

    private void jBtnAlterarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarBataglinActionPerformed
        // TODO add your handling code here:
         habilitar(true);
    }//GEN-LAST:event_jBtnAlterarBataglinActionPerformed

    private void jBtnCancelarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarBataglinActionPerformed
        // TODO add your handling code here:
         habilitar(false);
    }//GEN-LAST:event_jBtnCancelarBataglinActionPerformed

    private void jBtnConfirmarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarBataglinActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnConfirmarBataglinActionPerformed

    private void jBtnPesquisarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarBataglinActionPerformed
        // TODO add your handling code here:
          JOptionPane.showConfirmDialog(null, "Informe o código de usuário");
    }//GEN-LAST:event_jBtnPesquisarBataglinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMcbUsuario dialog = new JDlgMcbUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblApelidoBataglin;
    private javax.swing.JLabel JLblCPFBataglin;
    private javax.swing.JLabel JLblCodigoBataglin;
    private javax.swing.JLabel JLblDataNascBataglin;
    private javax.swing.JLabel JLblNivelBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JButton jBtnAlterarBataglin;
    private javax.swing.JButton jBtnCancelarBataglin;
    private javax.swing.JButton jBtnConfirmarBataglin;
    private javax.swing.JButton jBtnExcluirBataglin;
    private javax.swing.JButton jBtnPesquisarBataglin;
    private javax.swing.JButton jBtnincluirBataglin;
    private javax.swing.JCheckBox jChbAtivoBataglin1;
    private javax.swing.JComboBox<String> jCmoNivelBataglin;
    private javax.swing.JFormattedTextField jFmtCPFBataglin;
    private javax.swing.JFormattedTextField jFmtDataBataglin;
    private javax.swing.JPasswordField jPwfSenhaBataglin;
    private javax.swing.JTextField jTxtApelidoBataglin;
    private javax.swing.JTextField jTxtCodigoBataglin;
    private javax.swing.JTextField jTxtNomeBataglin;
    // End of variables declaration//GEN-END:variables
}