/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u07788816108
 */
public class JDlgFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgFornecedor
     */
    public JDlgFornecedor(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedor");
        setLocationRelativeTo(null);
        habilitar(false);
    }

        public void habilitar(boolean valor) {
        jTxtMcbNomeEmp.setEnabled(valor);
        jTxtMcbEmail.setEnabled(valor);
        jFmtMcbNumero.setEnabled(valor);
        jFmtMcbTelefone.setEnabled(valor);
        jTxtMcbRua.setEnabled(valor);
        jFmtMcbCPF.setEnabled(valor);
        jFmtMcbCNPJ.setEnabled(valor);
        jChbMcbAtivo.setEnabled(valor);
        jTxtMcbCodigo.setEnabled(valor);
        jPwfMcbSenha.setEnabled(valor);
        jFmtMcbTipoPes.setEnabled(valor);
        jCboMcbTipoPag.setEnabled(valor);
        jFmtMcbCEP.setEnabled(valor);
        jTxtMcbBairro.setEnabled(valor);
        jTxtMcbCidade.setEnabled(valor);
        jTxtMcbEstado.setEnabled(valor);
        jFmtMcbNumero.setEnabled(valor);
        jBtnMcbCancelar.setEnabled(valor);
        jCboMcbAtivo.setEnabled(valor);
        jBtnMcbConfirmar.setEnabled(valor);
        jBtnMcbIncluir.setEnabled(!valor);
        jBtnMcbAlterar.setEnabled(!valor);
        jBtnMcbExcluir.setEnabled(!valor);
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jChbMcbAtivo = new javax.swing.JCheckBox();
        jTxtMcbRua = new javax.swing.JTextField();
        jFmtMcbNumero = new javax.swing.JFormattedTextField();
        jFmtMcbCEP = new javax.swing.JFormattedTextField();
        JLblNomeBataglin = new javax.swing.JLabel();
        jFmtMcbCNPJ = new javax.swing.JFormattedTextField();
        JLblCEPBataglin = new javax.swing.JLabel();
        jFmtMcbCPF = new javax.swing.JFormattedTextField();
        JLblCidadeBataglin = new javax.swing.JLabel();
        jFmtMcbTipoPes = new javax.swing.JFormattedTextField();
        JLblBairroBataglin = new javax.swing.JLabel();
        JLblCPFBataglin = new javax.swing.JLabel();
        jFmtMcbTelefone = new javax.swing.JFormattedTextField();
        JLblEmailBataglin = new javax.swing.JLabel();
        jPwfMcbSenha = new javax.swing.JPasswordField();
        JLblTelefoneBataglin = new javax.swing.JLabel();
        JLblEstadoBataglin = new javax.swing.JLabel();
        JLblRuaBataglin = new javax.swing.JLabel();
        jBtnMcbIncluir = new javax.swing.JButton();
        JLblTipoPesBataglin = new javax.swing.JLabel();
        jBtnMcbExcluir = new javax.swing.JButton();
        JLblSexoBataglin = new javax.swing.JLabel();
        jBtnMcbAlterar = new javax.swing.JButton();
        JLblSenhaBataglin = new javax.swing.JLabel();
        jBtnMcbCancelar = new javax.swing.JButton();
        jTxtMcbNomeEmp = new javax.swing.JTextField();
        jBtnMcbConfirmar = new javax.swing.JButton();
        jTxtMcbEmail = new javax.swing.JTextField();
        jTxtMcbBairro = new javax.swing.JTextField();
        jTxtMcbCodigo = new javax.swing.JTextField();
        JLblCodigoBataglin = new javax.swing.JLabel();
        jTxtMcbCidade = new javax.swing.JTextField();
        jTxtMcbEstado = new javax.swing.JTextField();
        JLblCNPJBataglin = new javax.swing.JLabel();
        JLblEnderecoBataglin = new javax.swing.JLabel();
        jCboMcbTipoPag = new javax.swing.JComboBox<>();
        jBtnMcbPesquisar = new javax.swing.JButton();
        jCboMcbAtivo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jChbMcbAtivo.setText("Ativo");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLblNomeBataglin.setText("Nome Empresa");

        JLblCEPBataglin.setText("CEP");

        JLblCidadeBataglin.setText("Cidade");

        JLblBairroBataglin.setText("Bairro");

        JLblCPFBataglin.setText("CPF");

        JLblEmailBataglin.setText("Email");

        JLblTelefoneBataglin.setText("Telefone");

        JLblEstadoBataglin.setText("Estado");

        JLblRuaBataglin.setText("Rua");

        jBtnMcbIncluir.setBackground(new java.awt.Color(168, 245, 252));
        jBtnMcbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnMcbIncluir.setText("Incluir");
        jBtnMcbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbIncluirActionPerformed(evt);
            }
        });

        JLblTipoPesBataglin.setText("Tipo/Pessoa");

        jBtnMcbExcluir.setBackground(new java.awt.Color(255, 102, 102));
        jBtnMcbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnMcbExcluir.setText("Excluir");
        jBtnMcbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbExcluirActionPerformed(evt);
            }
        });

        JLblSexoBataglin.setText("Tipo/Pagamento");

        jBtnMcbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnMcbAlterar.setText("Alterar");
        jBtnMcbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbAlterarActionPerformed(evt);
            }
        });

        JLblSenhaBataglin.setText("Senha");

        jBtnMcbCancelar.setBackground(new java.awt.Color(153, 204, 255));
        jBtnMcbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnMcbCancelar.setText("Cancelar");
        jBtnMcbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbCancelarActionPerformed(evt);
            }
        });

        jBtnMcbConfirmar.setBackground(new java.awt.Color(0, 153, 51));
        jBtnMcbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnMcbConfirmar.setText("Confirmar");
        jBtnMcbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbConfirmarActionPerformed(evt);
            }
        });

        JLblCodigoBataglin.setText("Código");

        JLblCNPJBataglin.setText("CNPJ");

        JLblEnderecoBataglin.setText("Número");

        jCboMcbTipoPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnMcbPesquisar.setBackground(new java.awt.Color(51, 153, 255));
        jBtnMcbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnMcbPesquisar.setText("Pesquisar");
        jBtnMcbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbPesquisarActionPerformed(evt);
            }
        });

        jCboMcbAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLblNomeBataglin)
                            .addComponent(JLblCEPBataglin)
                            .addComponent(JLblCNPJBataglin)
                            .addComponent(jFmtMcbCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jFmtMcbCNPJ)
                            .addComponent(jTxtMcbNomeEmp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtMcbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblEmailBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblTelefoneBataglin)
                                    .addComponent(jFmtMcbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtMcbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblCPFBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblTipoPesBataglin)
                                    .addComponent(jFmtMcbTipoPes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblSexoBataglin)
                                    .addComponent(jCboMcbTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblEstadoBataglin)
                                    .addComponent(jTxtMcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblBairroBataglin)
                                    .addComponent(jTxtMcbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtMcbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblCidadeBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtMcbRua, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblRuaBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblEnderecoBataglin)
                                    .addComponent(jFmtMcbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(JLblCodigoBataglin)
                                .addGap(275, 275, 275)
                                .addComponent(JLblSenhaBataglin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnMcbIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnMcbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnMcbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnMcbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jTxtMcbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jPwfMcbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jBtnMcbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jBtnMcbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCboMcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblNomeBataglin)
                    .addComponent(JLblEmailBataglin)
                    .addComponent(JLblTelefoneBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMcbNomeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMcbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtMcbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLblCNPJBataglin)
                        .addComponent(JLblCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLblTipoPesBataglin)
                        .addComponent(JLblSexoBataglin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtMcbCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtMcbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtMcbTipoPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboMcbTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblCEPBataglin)
                    .addComponent(JLblEstadoBataglin)
                    .addComponent(JLblBairroBataglin)
                    .addComponent(JLblRuaBataglin)
                    .addComponent(JLblEnderecoBataglin)
                    .addComponent(JLblCidadeBataglin))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMcbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMcbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMcbRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtMcbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtMcbCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblSenhaBataglin)
                    .addComponent(JLblCodigoBataglin)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfMcbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMcbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboMcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMcbIncluir)
                    .addComponent(jBtnMcbExcluir)
                    .addComponent(jBtnMcbAlterar)
                    .addComponent(jBtnMcbCancelar)
                    .addComponent(jBtnMcbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMcbPesquisar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMcbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbIncluirActionPerformed
        // TODO add your handling code here:
         habilitar(true);
    }//GEN-LAST:event_jBtnMcbIncluirActionPerformed

    private void jBtnMcbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Tem certeza que deseja continuar? Essa ação não pode ser desfeita",
"Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnMcbExcluirActionPerformed

    private void jBtnMcbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbAlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnMcbAlterarActionPerformed

    private void jBtnMcbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbCancelarActionPerformed
        // TODO add your handling code here:
          habilitar(false);
    }//GEN-LAST:event_jBtnMcbCancelarActionPerformed

    private void jBtnMcbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbConfirmarActionPerformed
        // TODO add your handling code here:
           habilitar(false);
    }//GEN-LAST:event_jBtnMcbConfirmarActionPerformed

    private void jBtnMcbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Informe o código de fornecedor"
                + "");
    }//GEN-LAST:event_jBtnMcbPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFornecedor dialog = new JDlgFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblBairroBataglin;
    private javax.swing.JLabel JLblCEPBataglin;
    private javax.swing.JLabel JLblCNPJBataglin;
    private javax.swing.JLabel JLblCPFBataglin;
    private javax.swing.JLabel JLblCidadeBataglin;
    private javax.swing.JLabel JLblCodigoBataglin;
    private javax.swing.JLabel JLblEmailBataglin;
    private javax.swing.JLabel JLblEnderecoBataglin;
    private javax.swing.JLabel JLblEstadoBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblRuaBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JLabel JLblSexoBataglin;
    private javax.swing.JLabel JLblTelefoneBataglin;
    private javax.swing.JLabel JLblTipoPesBataglin;
    private javax.swing.JButton jBtnMcbAlterar;
    private javax.swing.JButton jBtnMcbCancelar;
    private javax.swing.JButton jBtnMcbConfirmar;
    private javax.swing.JButton jBtnMcbExcluir;
    private javax.swing.JButton jBtnMcbIncluir;
    private javax.swing.JButton jBtnMcbPesquisar;
    private javax.swing.JComboBox<String> jCboMcbAtivo;
    private javax.swing.JComboBox<String> jCboMcbTipoPag;
    private javax.swing.JCheckBox jChbMcbAtivo;
    private javax.swing.JFormattedTextField jFmtMcbCEP;
    private javax.swing.JFormattedTextField jFmtMcbCNPJ;
    private javax.swing.JFormattedTextField jFmtMcbCPF;
    private javax.swing.JFormattedTextField jFmtMcbNumero;
    private javax.swing.JFormattedTextField jFmtMcbTelefone;
    private javax.swing.JFormattedTextField jFmtMcbTipoPes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPwfMcbSenha;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTxtMcbBairro;
    private javax.swing.JTextField jTxtMcbCidade;
    private javax.swing.JTextField jTxtMcbCodigo;
    private javax.swing.JTextField jTxtMcbEmail;
    private javax.swing.JTextField jTxtMcbEstado;
    private javax.swing.JTextField jTxtMcbNomeEmp;
    private javax.swing.JTextField jTxtMcbRua;
    // End of variables declaration//GEN-END:variables
}
