/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u07788816108
 */
public class JDlgFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgFornecedor
     */
    public JDlgFornecedor(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedor");
        setLocationRelativeTo(null);
        habilitar(false);
    }

        public void habilitar(boolean valor) {
        jTxtNomeEmpBataglin.setEnabled(valor);
        jTxtEmailBataglin.setEnabled(valor);
        jFmtNumeroBataglin.setEnabled(valor);
        jFmtTelefoneBataglin.setEnabled(valor);
        jTxtRuaBataglin.setEnabled(valor);
        jFmtCPFBataglin.setEnabled(valor);
        jFmtCNPJBataglin.setEnabled(valor);
        jChbAtivoBataglin1.setEnabled(valor);
        jTxtCodigoBataglin.setEnabled(valor);
        jPwfSenhaBataglin.setEnabled(valor);
        jFmtTipoPesBataglin.setEnabled(valor);
        jCboTipoPagBataglin.setEnabled(valor);
        jFmtCEPBataglin.setEnabled(valor);
        jTxtBairroBataglin.setEnabled(valor);
        jTxtCidadeBataglin.setEnabled(valor);
        jTxtEstadoBataglin.setEnabled(valor);
        jFmtNumeroBataglin.setEnabled(valor);
        jBtnCancelarBataglin.setEnabled(valor);
        jBtnConfirmarBataglin.setEnabled(valor);
        jBtnIncluirBataglin.setEnabled(!valor);
        jBtnAlterarBataglin.setEnabled(!valor);
        jBtnExcluirBataglin.setEnabled(!valor);
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jTxtRuaBataglin = new javax.swing.JTextField();
        jFmtNumeroBataglin = new javax.swing.JFormattedTextField();
        jFmtCEPBataglin = new javax.swing.JFormattedTextField();
        JLblNomeBataglin = new javax.swing.JLabel();
        jFmtCNPJBataglin = new javax.swing.JFormattedTextField();
        JLblCEPBataglin = new javax.swing.JLabel();
        jFmtCPFBataglin = new javax.swing.JFormattedTextField();
        JLblCidadeBataglin = new javax.swing.JLabel();
        jFmtTipoPesBataglin = new javax.swing.JFormattedTextField();
        JLblBairroBataglin = new javax.swing.JLabel();
        JLblCPFBataglin = new javax.swing.JLabel();
        jFmtTelefoneBataglin = new javax.swing.JFormattedTextField();
        JLblEmailBataglin = new javax.swing.JLabel();
        jPwfSenhaBataglin = new javax.swing.JPasswordField();
        JLblTelefoneBataglin = new javax.swing.JLabel();
        JLblEstadoBataglin = new javax.swing.JLabel();
        JLblRuaBataglin = new javax.swing.JLabel();
        jBtnIncluirBataglin = new javax.swing.JButton();
        JLblTipoPesBataglin = new javax.swing.JLabel();
        jBtnExcluirBataglin = new javax.swing.JButton();
        JLblSexoBataglin = new javax.swing.JLabel();
        jBtnAlterarBataglin = new javax.swing.JButton();
        JLblSenhaBataglin = new javax.swing.JLabel();
        jBtnCancelarBataglin = new javax.swing.JButton();
        jTxtNomeEmpBataglin = new javax.swing.JTextField();
        jBtnConfirmarBataglin = new javax.swing.JButton();
        jTxtEmailBataglin = new javax.swing.JTextField();
        jTxtBairroBataglin = new javax.swing.JTextField();
        jTxtCodigoBataglin = new javax.swing.JTextField();
        JLblCodigoBataglin = new javax.swing.JLabel();
        jTxtCidadeBataglin = new javax.swing.JTextField();
        jTxtEstadoBataglin = new javax.swing.JTextField();
        JLblCNPJBataglin = new javax.swing.JLabel();
        JLblEnderecoBataglin = new javax.swing.JLabel();
        jCboTipoPagBataglin = new javax.swing.JComboBox<>();
        jChbAtivoBataglin1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLblNomeBataglin.setText("Nome Empresa");

        JLblCEPBataglin.setText("CEP");

        JLblCidadeBataglin.setText("Cidade");

        JLblBairroBataglin.setText("Bairro");

        JLblCPFBataglin.setText("CPF");

        JLblEmailBataglin.setText("Email");

        JLblTelefoneBataglin.setText("Telefone");

        JLblEstadoBataglin.setText("Estado");

        JLblRuaBataglin.setText("Rua");

        jBtnIncluirBataglin.setBackground(new java.awt.Color(168, 245, 252));
        jBtnIncluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluirBataglin.setText("Incluir");
        jBtnIncluirBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirBataglinActionPerformed(evt);
            }
        });

        JLblTipoPesBataglin.setText("Tipo/Pessoa");

        jBtnExcluirBataglin.setBackground(new java.awt.Color(255, 102, 102));
        jBtnExcluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluirBataglin.setText("Excluir");
        jBtnExcluirBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirBataglinActionPerformed(evt);
            }
        });

        JLblSexoBataglin.setText("Tipo/Pagamento");

        jBtnAlterarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterarBataglin.setText("Alterar");
        jBtnAlterarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarBataglinActionPerformed(evt);
            }
        });

        JLblSenhaBataglin.setText("Senha");

        jBtnCancelarBataglin.setBackground(new java.awt.Color(153, 204, 255));
        jBtnCancelarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelarBataglin.setText("Cancelar");
        jBtnCancelarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarBataglinActionPerformed(evt);
            }
        });

        jBtnConfirmarBataglin.setBackground(new java.awt.Color(0, 153, 51));
        jBtnConfirmarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmarBataglin.setText("Confirmar");
        jBtnConfirmarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarBataglinActionPerformed(evt);
            }
        });

        JLblCodigoBataglin.setText("Código");

        JLblCNPJBataglin.setText("CNPJ");

        JLblEnderecoBataglin.setText("Número");

        jCboTipoPagBataglin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jChbAtivoBataglin1.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLblNomeBataglin)
                            .addComponent(JLblCEPBataglin)
                            .addComponent(JLblCNPJBataglin)
                            .addComponent(jFmtCEPBataglin, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jFmtCNPJBataglin)
                            .addComponent(jTxtNomeEmpBataglin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtEmailBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblEmailBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblTelefoneBataglin)
                                    .addComponent(jFmtTelefoneBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblCPFBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblTipoPesBataglin)
                                    .addComponent(jFmtTipoPesBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblSexoBataglin)
                                    .addComponent(jCboTipoPagBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblEstadoBataglin)
                                    .addComponent(jTxtEstadoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblBairroBataglin)
                                    .addComponent(jTxtBairroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtCidadeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblCidadeBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtRuaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblRuaBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblEnderecoBataglin)
                                    .addComponent(jFmtNumeroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(JLblCodigoBataglin)
                                .addGap(275, 275, 275)
                                .addComponent(JLblSenhaBataglin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnExcluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAlterarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnCancelarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jTxtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jChbAtivoBataglin1)
                                .addContainerGap(104, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblNomeBataglin)
                    .addComponent(JLblEmailBataglin)
                    .addComponent(JLblTelefoneBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNomeEmpBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmailBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTelefoneBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLblCNPJBataglin)
                        .addComponent(JLblCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLblTipoPesBataglin)
                        .addComponent(JLblSexoBataglin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCNPJBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTipoPesBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboTipoPagBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblCEPBataglin)
                    .addComponent(JLblEstadoBataglin)
                    .addComponent(JLblBairroBataglin)
                    .addComponent(JLblRuaBataglin)
                    .addComponent(JLblEnderecoBataglin)
                    .addComponent(JLblCidadeBataglin))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCidadeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEstadoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBairroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRuaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtNumeroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCEPBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblSenhaBataglin)
                    .addComponent(JLblCodigoBataglin))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivoBataglin1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluirBataglin)
                    .addComponent(jBtnExcluirBataglin)
                    .addComponent(jBtnAlterarBataglin)
                    .addComponent(jBtnCancelarBataglin)
                    .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirBataglinActionPerformed
        // TODO add your handling code here:
         habilitar(true);
    }//GEN-LAST:event_jBtnIncluirBataglinActionPerformed

    private void jBtnExcluirBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirBataglinActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Tem certeza que deseja continuar? Essa ação não pode ser desfeita",
"Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnExcluirBataglinActionPerformed

    private void jBtnAlterarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarBataglinActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnAlterarBataglinActionPerformed

    private void jBtnCancelarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarBataglinActionPerformed
        // TODO add your handling code here:
          habilitar(false);
    }//GEN-LAST:event_jBtnCancelarBataglinActionPerformed

    private void jBtnConfirmarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarBataglinActionPerformed
        // TODO add your handling code here:
           habilitar(false);
    }//GEN-LAST:event_jBtnConfirmarBataglinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFornecedor dialog = new JDlgFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblBairroBataglin;
    private javax.swing.JLabel JLblCEPBataglin;
    private javax.swing.JLabel JLblCNPJBataglin;
    private javax.swing.JLabel JLblCPFBataglin;
    private javax.swing.JLabel JLblCidadeBataglin;
    private javax.swing.JLabel JLblCodigoBataglin;
    private javax.swing.JLabel JLblEmailBataglin;
    private javax.swing.JLabel JLblEnderecoBataglin;
    private javax.swing.JLabel JLblEstadoBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblRuaBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JLabel JLblSexoBataglin;
    private javax.swing.JLabel JLblTelefoneBataglin;
    private javax.swing.JLabel JLblTipoPesBataglin;
    private javax.swing.JButton jBtnAlterarBataglin;
    private javax.swing.JButton jBtnCancelarBataglin;
    private javax.swing.JButton jBtnConfirmarBataglin;
    private javax.swing.JButton jBtnExcluirBataglin;
    private javax.swing.JButton jBtnIncluirBataglin;
    private javax.swing.JComboBox<String> jCboTipoPagBataglin;
    private javax.swing.JCheckBox jChbAtivoBataglin1;
    private javax.swing.JFormattedTextField jFmtCEPBataglin;
    private javax.swing.JFormattedTextField jFmtCNPJBataglin;
    private javax.swing.JFormattedTextField jFmtCPFBataglin;
    private javax.swing.JFormattedTextField jFmtNumeroBataglin;
    private javax.swing.JFormattedTextField jFmtTelefoneBataglin;
    private javax.swing.JFormattedTextField jFmtTipoPesBataglin;
    private javax.swing.JPasswordField jPwfSenhaBataglin;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTxtBairroBataglin;
    private javax.swing.JTextField jTxtCidadeBataglin;
    private javax.swing.JTextField jTxtCodigoBataglin;
    private javax.swing.JTextField jTxtEmailBataglin;
    private javax.swing.JTextField jTxtEstadoBataglin;
    private javax.swing.JTextField jTxtNomeEmpBataglin;
    private javax.swing.JTextField jTxtRuaBataglin;
    // End of variables declaration//GEN-END:variables
}
