/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u07788816108
 */
public class JDlgMcbVendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMcbVendedor
     */
    public JDlgMcbVendedor(java.awt.Frame parent, boolean modal) {
             super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedor");
        setLocationRelativeTo(null);
        habilitar(false);
    }
    
        public void habilitar(boolean valor) {
        jTxtNomeBataglin.setEnabled(valor);
        jTxtEmailBataglin.setEnabled(valor);
        jFmtCPFBataglin.setEnabled(valor);
        jFmtCodigoBataglin.setEnabled(valor);
        jFmtDataContrBataglin.setEnabled(valor);
        jFmtTelefoneBataglin.setEnabled(valor);
        jPwfSenhaBataglin.setEnabled(valor);
        jBtnCancelarBataglin.setEnabled(valor);
        jBtnConfirmarBataglin.setEnabled(valor);
        jBtnIncluirBataglin.setEnabled(!valor);
        jBtnAlterarBataglin.setEnabled(!valor);
        jBtnExcluirBataglin.setEnabled(!valor);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBtnIncluirBataglin = new javax.swing.JButton();
        jBtnExcluirBataglin = new javax.swing.JButton();
        jBtnAlterarBataglin = new javax.swing.JButton();
        jBtnCancelarBataglin = new javax.swing.JButton();
        jBtnConfirmarBataglin = new javax.swing.JButton();
        JLblNomeBataglin = new javax.swing.JLabel();
        JLblDataContrBataglin = new javax.swing.JLabel();
        JLblEmailBataglin = new javax.swing.JLabel();
        JLblTelefoneBataglin = new javax.swing.JLabel();
        jPwfSenhaBataglin = new javax.swing.JPasswordField();
        JLblSenhaBataglin = new javax.swing.JLabel();
        JLblCodigoBataglin = new javax.swing.JLabel();
        JLblCPFBataglin = new javax.swing.JLabel();
        jFmtCodigoBataglin = new javax.swing.JFormattedTextField();
        jTxtEmailBataglin = new javax.swing.JTextField();
        jTxtNomeBataglin = new javax.swing.JTextField();
        jFmtDataContrBataglin = new javax.swing.JFormattedTextField();
        jFmtTelefoneBataglin = new javax.swing.JFormattedTextField();
        jFmtCPFBataglin = new javax.swing.JFormattedTextField();
        jChbAtivoBataglin1 = new javax.swing.JCheckBox();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnIncluirBataglin.setBackground(new java.awt.Color(168, 245, 252));
        jBtnIncluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluirBataglin.setText("Incluir");
        jBtnIncluirBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirBataglinActionPerformed(evt);
            }
        });

        jBtnExcluirBataglin.setBackground(new java.awt.Color(255, 102, 102));
        jBtnExcluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluirBataglin.setText("Excluir");
        jBtnExcluirBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirBataglinActionPerformed(evt);
            }
        });

        jBtnAlterarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterarBataglin.setText("Alterar");
        jBtnAlterarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarBataglinActionPerformed(evt);
            }
        });

        jBtnCancelarBataglin.setBackground(new java.awt.Color(153, 204, 255));
        jBtnCancelarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelarBataglin.setText("Cancelar");
        jBtnCancelarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarBataglinActionPerformed(evt);
            }
        });

        jBtnConfirmarBataglin.setBackground(new java.awt.Color(0, 153, 51));
        jBtnConfirmarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmarBataglin.setText("Confirmar");
        jBtnConfirmarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarBataglinActionPerformed(evt);
            }
        });

        JLblNomeBataglin.setText("Nome");

        JLblDataContrBataglin.setText("Data de Contrato");

        JLblEmailBataglin.setText("Email");

        JLblTelefoneBataglin.setText("Telefone");

        JLblSenhaBataglin.setText("Senha");

        JLblCodigoBataglin.setText("Código");

        JLblCPFBataglin.setText("CPF");

        jChbAtivoBataglin1.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(JLblCodigoBataglin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLblSenhaBataglin)
                .addGap(389, 389, 389))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblCPFBataglin)
                            .addComponent(JLblNomeBataglin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnIncluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNomeBataglin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCPFBataglin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblDataContrBataglin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFmtDataContrBataglin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(JLblEmailBataglin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmailBataglin, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblTelefoneBataglin)
                            .addComponent(jFmtTelefoneBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jBtnExcluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnAlterarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCancelarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jChbAtivoBataglin1)
                            .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblNomeBataglin)
                    .addComponent(JLblEmailBataglin)
                    .addComponent(JLblTelefoneBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmailBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTelefoneBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblDataContrBataglin)
                    .addComponent(JLblCPFBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtDataContrBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblSenhaBataglin)
                    .addComponent(JLblCodigoBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivoBataglin1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluirBataglin)
                    .addComponent(jBtnExcluirBataglin)
                    .addComponent(jBtnAlterarBataglin)
                    .addComponent(jBtnCancelarBataglin)
                    .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirBataglinActionPerformed
        // TODO add your handling code here:
         habilitar(true);
    }//GEN-LAST:event_jBtnIncluirBataglinActionPerformed

    private void jBtnExcluirBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirBataglinActionPerformed
        // TODO add your handling code here:
           JOptionPane.showConfirmDialog(null, "Tem certeza que deseja continuar? Essa ação não pode ser desfeita",
"Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnExcluirBataglinActionPerformed

    private void jBtnAlterarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarBataglinActionPerformed
        // TODO add your handling code here:
            habilitar(true);
    }//GEN-LAST:event_jBtnAlterarBataglinActionPerformed

    private void jBtnCancelarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarBataglinActionPerformed
        // TODO add your handling code here:
         habilitar(false);
    }//GEN-LAST:event_jBtnCancelarBataglinActionPerformed

    private void jBtnConfirmarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarBataglinActionPerformed
        // TODO add your handling code here:
           habilitar(false);
    }//GEN-LAST:event_jBtnConfirmarBataglinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMcbVendedor dialog = new JDlgMcbVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblCPFBataglin;
    private javax.swing.JLabel JLblCodigoBataglin;
    private javax.swing.JLabel JLblDataContrBataglin;
    private javax.swing.JLabel JLblEmailBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JLabel JLblTelefoneBataglin;
    private javax.swing.JButton jBtnAlterarBataglin;
    private javax.swing.JButton jBtnCancelarBataglin;
    private javax.swing.JButton jBtnConfirmarBataglin;
    private javax.swing.JButton jBtnExcluirBataglin;
    private javax.swing.JButton jBtnIncluirBataglin;
    private javax.swing.JCheckBox jChbAtivoBataglin1;
    private javax.swing.JFormattedTextField jFmtCPFBataglin;
    private javax.swing.JFormattedTextField jFmtCodigoBataglin;
    private javax.swing.JFormattedTextField jFmtDataContrBataglin;
    private javax.swing.JFormattedTextField jFmtTelefoneBataglin;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPwfSenhaBataglin;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtEmailBataglin;
    private javax.swing.JTextField jTxtNomeBataglin;
    // End of variables declaration//GEN-END:variables
}
