/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 *
 * @author u07788816108
 */
public class JDlgFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgFornecedor
     */
    public JDlgFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        JTxtRuaBataglin = new javax.swing.JTextField();
        JFmtNumeroBataglin = new javax.swing.JFormattedTextField();
        JFmtCEPBataglin = new javax.swing.JFormattedTextField();
        JLblNomeBataglin = new javax.swing.JLabel();
        JFmtCNPJBataglin = new javax.swing.JFormattedTextField();
        JLblCEPBataglin = new javax.swing.JLabel();
        JFmtCPFBataglin = new javax.swing.JFormattedTextField();
        JLblCidadeBataglin = new javax.swing.JLabel();
        JFmtTipoPesBataglin = new javax.swing.JFormattedTextField();
        JLblBairroBataglin = new javax.swing.JLabel();
        JLblCPFBataglin = new javax.swing.JLabel();
        JFmtTelefoneBatatglin = new javax.swing.JFormattedTextField();
        JLblEmailBataglin = new javax.swing.JLabel();
        JPwfSenhaBataglin = new javax.swing.JPasswordField();
        JLblTelefoneBataglin = new javax.swing.JLabel();
        JLblEstadoBataglin = new javax.swing.JLabel();
        JLblRuaBataglin = new javax.swing.JLabel();
        JBtnIncluirBataglin = new javax.swing.JButton();
        JLblTipoPesBataglin = new javax.swing.JLabel();
        JBtnExcluirBataglin = new javax.swing.JButton();
        JLblSexoBataglin = new javax.swing.JLabel();
        JBtnAlterarBataglin = new javax.swing.JButton();
        JLblSenhaBataglin = new javax.swing.JLabel();
        JBtnCancelarBataglin = new javax.swing.JButton();
        JTxtNomeEmpBataglin = new javax.swing.JTextField();
        JBtnConfirmarBataglin = new javax.swing.JButton();
        JTxtEmailBataglin = new javax.swing.JTextField();
        JTxtBairroBataglin = new javax.swing.JTextField();
        JTxtCodigoBataglin = new javax.swing.JTextField();
        JLblCodigoBataglin = new javax.swing.JLabel();
        JTxtCidadeBataglin = new javax.swing.JTextField();
        JTxtEstadoBataglin = new javax.swing.JTextField();
        JLblCNPJBataglin = new javax.swing.JLabel();
        JLblEnderecoBataglin = new javax.swing.JLabel();
        JCboTipoPagBataglin = new javax.swing.JComboBox<>();
        JChbAtivoBataglin1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JFmtNumeroBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFmtNumeroBataglinActionPerformed(evt);
            }
        });

        JLblNomeBataglin.setText("Nome Empresa");

        JLblCEPBataglin.setText("CEP");

        JLblCidadeBataglin.setText("Cidade");

        JLblBairroBataglin.setText("Bairro");

        JLblCPFBataglin.setText("CPF");

        JLblEmailBataglin.setText("Email");

        JLblTelefoneBataglin.setText("Telefone");

        JLblEstadoBataglin.setText("Estado");

        JLblRuaBataglin.setText("Rua");

        JBtnIncluirBataglin.setBackground(new java.awt.Color(168, 245, 252));
        JBtnIncluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        JBtnIncluirBataglin.setText("Incluir");

        JLblTipoPesBataglin.setText("Tipo/Pessoa");

        JBtnExcluirBataglin.setBackground(new java.awt.Color(255, 102, 102));
        JBtnExcluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        JBtnExcluirBataglin.setText("Excluir");

        JLblSexoBataglin.setText("Tipo/Pagamento");

        JBtnAlterarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        JBtnAlterarBataglin.setText("Alterar");

        JLblSenhaBataglin.setText("Senha");

        JBtnCancelarBataglin.setBackground(new java.awt.Color(153, 204, 255));
        JBtnCancelarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        JBtnCancelarBataglin.setText("Cancelar");
        JBtnCancelarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCancelarBataglinActionPerformed(evt);
            }
        });

        JTxtNomeEmpBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtNomeEmpBataglinActionPerformed(evt);
            }
        });

        JBtnConfirmarBataglin.setBackground(new java.awt.Color(0, 153, 51));
        JBtnConfirmarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        JBtnConfirmarBataglin.setText("Confirmar");

        JTxtBairroBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtBairroBataglinActionPerformed(evt);
            }
        });

        JLblCodigoBataglin.setText("Código");

        JTxtCidadeBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtCidadeBataglinActionPerformed(evt);
            }
        });

        JLblCNPJBataglin.setText("CNPJ");

        JLblEnderecoBataglin.setText("Número");

        JCboTipoPagBataglin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JChbAtivoBataglin1.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLblNomeBataglin)
                            .addComponent(JLblCEPBataglin)
                            .addComponent(JLblCNPJBataglin)
                            .addComponent(JFmtCEPBataglin, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(JFmtCNPJBataglin)
                            .addComponent(JTxtNomeEmpBataglin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTxtEmailBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblEmailBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblTelefoneBataglin)
                                    .addComponent(JFmtTelefoneBatatglin, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JFmtCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblCPFBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblTipoPesBataglin)
                                    .addComponent(JFmtTipoPesBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblSexoBataglin)
                                    .addComponent(JCboTipoPagBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblEstadoBataglin)
                                    .addComponent(JTxtEstadoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblBairroBataglin)
                                    .addComponent(JTxtBairroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTxtCidadeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblCidadeBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTxtRuaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblRuaBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblEnderecoBataglin)
                                    .addComponent(JFmtNumeroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(JLblCodigoBataglin)
                                .addGap(275, 275, 275)
                                .addComponent(JLblSenhaBataglin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBtnIncluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBtnExcluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBtnAlterarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBtnCancelarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(JTxtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(JPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JChbAtivoBataglin1)
                            .addComponent(JBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblNomeBataglin)
                    .addComponent(JLblEmailBataglin)
                    .addComponent(JLblTelefoneBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtNomeEmpBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtEmailBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFmtTelefoneBatatglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLblCNPJBataglin)
                        .addComponent(JLblCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLblTipoPesBataglin)
                        .addComponent(JLblSexoBataglin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JFmtCNPJBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFmtCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFmtTipoPesBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCboTipoPagBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblCEPBataglin)
                    .addComponent(JLblEstadoBataglin)
                    .addComponent(JLblBairroBataglin)
                    .addComponent(JLblRuaBataglin)
                    .addComponent(JLblEnderecoBataglin)
                    .addComponent(JLblCidadeBataglin))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtCidadeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtEstadoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtBairroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtRuaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFmtNumeroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFmtCEPBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblSenhaBataglin)
                    .addComponent(JLblCodigoBataglin))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JChbAtivoBataglin1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnIncluirBataglin)
                    .addComponent(JBtnExcluirBataglin)
                    .addComponent(JBtnAlterarBataglin)
                    .addComponent(JBtnCancelarBataglin)
                    .addComponent(JBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFmtNumeroBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFmtNumeroBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFmtNumeroBataglinActionPerformed

    private void JBtnCancelarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCancelarBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtnCancelarBataglinActionPerformed

    private void JTxtNomeEmpBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtNomeEmpBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtNomeEmpBataglinActionPerformed

    private void JTxtBairroBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtBairroBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtBairroBataglinActionPerformed

    private void JTxtCidadeBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtCidadeBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtCidadeBataglinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFornecedor dialog = new JDlgFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAlterarBataglin;
    private javax.swing.JButton JBtnCancelarBataglin;
    private javax.swing.JButton JBtnConfirmarBataglin;
    private javax.swing.JButton JBtnExcluirBataglin;
    private javax.swing.JButton JBtnIncluirBataglin;
    private javax.swing.JComboBox<String> JCboTipoPagBataglin;
    private javax.swing.JCheckBox JChbAtivoBataglin1;
    private javax.swing.JFormattedTextField JFmtCEPBataglin;
    private javax.swing.JFormattedTextField JFmtCNPJBataglin;
    private javax.swing.JFormattedTextField JFmtCPFBataglin;
    private javax.swing.JFormattedTextField JFmtNumeroBataglin;
    private javax.swing.JFormattedTextField JFmtTelefoneBatatglin;
    private javax.swing.JFormattedTextField JFmtTipoPesBataglin;
    private javax.swing.JLabel JLblBairroBataglin;
    private javax.swing.JLabel JLblCEPBataglin;
    private javax.swing.JLabel JLblCNPJBataglin;
    private javax.swing.JLabel JLblCPFBataglin;
    private javax.swing.JLabel JLblCidadeBataglin;
    private javax.swing.JLabel JLblCodigoBataglin;
    private javax.swing.JLabel JLblEmailBataglin;
    private javax.swing.JLabel JLblEnderecoBataglin;
    private javax.swing.JLabel JLblEstadoBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblRuaBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JLabel JLblSexoBataglin;
    private javax.swing.JLabel JLblTelefoneBataglin;
    private javax.swing.JLabel JLblTipoPesBataglin;
    private javax.swing.JPasswordField JPwfSenhaBataglin;
    private javax.swing.JTextField JTxtBairroBataglin;
    private javax.swing.JTextField JTxtCidadeBataglin;
    private javax.swing.JTextField JTxtCodigoBataglin;
    private javax.swing.JTextField JTxtEmailBataglin;
    private javax.swing.JTextField JTxtEstadoBataglin;
    private javax.swing.JTextField JTxtNomeEmpBataglin;
    private javax.swing.JTextField JTxtRuaBataglin;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
