/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u07788816108
 */
public class JDlgMcbProduto extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMcbProduto
     */
    public JDlgMcbProduto(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);
        habilitar(false);
    }
    
        public void habilitar(boolean valor) {
        jTxtNomeBataglin.setEnabled(valor);
        jTxtDescricaoBataglin.setEnabled(valor);
        jFmtPrecoBataglin.setEnabled(valor);
        jFmtCodBarrasBataglin.setEnabled(valor);
        jFmtTipoBataglin.setEnabled(valor);
        jFmtCodProdutoBataglin.setEnabled(valor);
        jChbAtivoBataglin.setEnabled(valor);
        jBtnCancelarBataglin.setEnabled(valor);
        jBtnConfirmarBataglin.setEnabled(valor);
        jBtnIncluirBataglin.setEnabled(!valor);
        jBtnAlterarBataglin.setEnabled(!valor);
        jBtnExcluirBataglin.setEnabled(!valor);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPwfSenhaBataglin = new javax.swing.JPasswordField();
        JLblSenhaBataglin = new javax.swing.JLabel();
        JCboAtivoBataglin = new javax.swing.JComboBox<>();
        JLblAtivoBataglin = new javax.swing.JLabel();
        JLblPrecoBataglin = new javax.swing.JLabel();
        jFmtCodBarrasBataglin = new javax.swing.JFormattedTextField();
        jBtnIncluirBataglin = new javax.swing.JButton();
        jFmtPrecoBataglin = new javax.swing.JFormattedTextField();
        JLblCodProdutoBataglin = new javax.swing.JLabel();
        jFmtTipoBataglin = new javax.swing.JFormattedTextField();
        jBtnExcluirBataglin = new javax.swing.JButton();
        jBtnAlterarBataglin = new javax.swing.JButton();
        JLblTipoBataglin = new javax.swing.JLabel();
        jBtnCancelarBataglin = new javax.swing.JButton();
        jFmtCodProdutoBataglin = new javax.swing.JFormattedTextField();
        jBtnConfirmarBataglin = new javax.swing.JButton();
        JLblNomeBataglin = new javax.swing.JLabel();
        jTxtDescricaoBataglin = new javax.swing.JTextField();
        JLblCodBarrasBataglin = new javax.swing.JLabel();
        JLblDescricaoBataglin = new javax.swing.JLabel();
        jTxtNomeBataglin = new javax.swing.JTextField();
        jChbAtivoBataglin = new javax.swing.JCheckBox();

        JPwfSenhaBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPwfSenhaBataglinActionPerformed(evt);
            }
        });

        JLblSenhaBataglin.setText("Senha");

        JCboAtivoBataglin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCboAtivoBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCboAtivoBataglinActionPerformed(evt);
            }
        });

        JLblAtivoBataglin.setText("Ativo");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLblPrecoBataglin.setText("Preço");

        jBtnIncluirBataglin.setBackground(new java.awt.Color(168, 245, 252));
        jBtnIncluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluirBataglin.setText("Incluir");
        jBtnIncluirBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirBataglinActionPerformed(evt);
            }
        });

        JLblCodProdutoBataglin.setText("Código/Produto");

        jBtnExcluirBataglin.setBackground(new java.awt.Color(255, 102, 102));
        jBtnExcluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluirBataglin.setText("Excluir");
        jBtnExcluirBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirBataglinActionPerformed(evt);
            }
        });

        jBtnAlterarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterarBataglin.setText("Alterar");
        jBtnAlterarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarBataglinActionPerformed(evt);
            }
        });

        JLblTipoBataglin.setText("Tipo");

        jBtnCancelarBataglin.setBackground(new java.awt.Color(153, 204, 255));
        jBtnCancelarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelarBataglin.setText("Cancelar");
        jBtnCancelarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarBataglinActionPerformed(evt);
            }
        });

        jBtnConfirmarBataglin.setBackground(new java.awt.Color(0, 153, 51));
        jBtnConfirmarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmarBataglin.setText("Confirmar");
        jBtnConfirmarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarBataglinActionPerformed(evt);
            }
        });

        JLblNomeBataglin.setText("Nome");

        JLblCodBarrasBataglin.setText("Código de Barras");

        JLblDescricaoBataglin.setText("Descrição");

        jChbAtivoBataglin.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(JLblCodProdutoBataglin))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblTipoBataglin)
                                    .addComponent(JLblNomeBataglin)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtCodProdutoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnIncluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNomeBataglin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtTipoBataglin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblCodBarrasBataglin)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFmtCodBarrasBataglin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(JLblDescricaoBataglin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtDescricaoBataglin, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblPrecoBataglin)
                                    .addComponent(jFmtPrecoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jBtnExcluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnAlterarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCancelarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChbAtivoBataglin)
                                    .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblNomeBataglin)
                    .addComponent(JLblDescricaoBataglin)
                    .addComponent(JLblPrecoBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDescricaoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtPrecoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblCodBarrasBataglin)
                    .addComponent(JLblTipoBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCodBarrasBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTipoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(JLblCodProdutoBataglin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCodProdutoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivoBataglin))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluirBataglin)
                    .addComponent(jBtnExcluirBataglin)
                    .addComponent(jBtnAlterarBataglin)
                    .addComponent(jBtnCancelarBataglin)
                    .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPwfSenhaBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPwfSenhaBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPwfSenhaBataglinActionPerformed

    private void JCboAtivoBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCboAtivoBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCboAtivoBataglinActionPerformed

    private void jBtnIncluirBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirBataglinActionPerformed
        // TODO add your handling code here:
         habilitar(true);
    }//GEN-LAST:event_jBtnIncluirBataglinActionPerformed

    private void jBtnExcluirBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirBataglinActionPerformed
        // TODO add your handling code here:
           JOptionPane.showConfirmDialog(null, "Tem certeza que deseja continuar? Essa ação não pode ser desfeita",
"Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnExcluirBataglinActionPerformed

    private void jBtnAlterarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarBataglinActionPerformed
        // TODO add your handling code here:
           habilitar(true);
    }//GEN-LAST:event_jBtnAlterarBataglinActionPerformed

    private void jBtnCancelarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarBataglinActionPerformed
        // TODO add your handling code here:
          habilitar(false);
    }//GEN-LAST:event_jBtnCancelarBataglinActionPerformed

    private void jBtnConfirmarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarBataglinActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnConfirmarBataglinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMcbProduto dialog = new JDlgMcbProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCboAtivoBataglin;
    private javax.swing.JLabel JLblAtivoBataglin;
    private javax.swing.JLabel JLblCodBarrasBataglin;
    private javax.swing.JLabel JLblCodProdutoBataglin;
    private javax.swing.JLabel JLblDescricaoBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblPrecoBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JLabel JLblTipoBataglin;
    private javax.swing.JPasswordField JPwfSenhaBataglin;
    private javax.swing.JButton jBtnAlterarBataglin;
    private javax.swing.JButton jBtnCancelarBataglin;
    private javax.swing.JButton jBtnConfirmarBataglin;
    private javax.swing.JButton jBtnExcluirBataglin;
    private javax.swing.JButton jBtnIncluirBataglin;
    private javax.swing.JCheckBox jChbAtivoBataglin;
    private javax.swing.JFormattedTextField jFmtCodBarrasBataglin;
    private javax.swing.JFormattedTextField jFmtCodProdutoBataglin;
    private javax.swing.JFormattedTextField jFmtPrecoBataglin;
    private javax.swing.JFormattedTextField jFmtTipoBataglin;
    private javax.swing.JTextField jTxtDescricaoBataglin;
    private javax.swing.JTextField jTxtNomeBataglin;
    // End of variables declaration//GEN-END:variables
}
