/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u07788816108
 */
public class JDlgMcbUsuario extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMcbUsuario
     */
    public JDlgMcbUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        habilitar(false);
    }

        public void habilitar(boolean valor) {
        jTxtMcbNome.setEnabled(valor);
        jFmtMcbCPF.setEnabled(valor);
        jTxtMcbApelido.setEnabled(valor);
        jFmtMcbData.setEnabled(valor);
        jChbAtivoBataglin1.setEnabled(valor);
        jTxtMcbCodigo.setEnabled(valor);
        jPwfMcbSenha.setEnabled(valor);
        jCboMcbNivel.setEnabled(valor);
        jBtnMcbCancelar.setEnabled(valor);
        jCboMcbAtivo.setEnabled(valor);
        jBtnMcbConfirmar.setEnabled(valor);
        jBtnMcbPesquisar.setEnabled(!valor);
        jBtnMcbincluir.setEnabled(!valor);
        jBtnMcbAlterar.setEnabled(!valor);
        jBtnMcbExcluir.setEnabled(!valor);
        }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChbAtivoBataglin1 = new javax.swing.JCheckBox();
        JLblCodigoBataglin = new javax.swing.JLabel();
        JLblNomeBataglin = new javax.swing.JLabel();
        JLblApelidoBataglin = new javax.swing.JLabel();
        JLblCPFBataglin = new javax.swing.JLabel();
        JLblDataNascBataglin = new javax.swing.JLabel();
        JLblNivelBataglin = new javax.swing.JLabel();
        JLblSenhaBataglin = new javax.swing.JLabel();
        jBtnMcbincluir = new javax.swing.JButton();
        jBtnMcbExcluir = new javax.swing.JButton();
        jBtnMcbAlterar = new javax.swing.JButton();
        jBtnMcbCancelar = new javax.swing.JButton();
        jBtnMcbConfirmar = new javax.swing.JButton();
        jBtnMcbPesquisar = new javax.swing.JButton();
        jCboMcbNivel = new javax.swing.JComboBox<>();
        jFmtMcbData = new javax.swing.JFormattedTextField();
        jFmtMcbCPF = new javax.swing.JFormattedTextField();
        jPwfMcbSenha = new javax.swing.JPasswordField();
        jTxtMcbCodigo = new javax.swing.JTextField();
        jTxtMcbNome = new javax.swing.JTextField();
        jTxtMcbApelido = new javax.swing.JTextField();
        jCboMcbAtivo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jChbAtivoBataglin1.setText("Ativo");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLblCodigoBataglin.setText("Código");

        JLblNomeBataglin.setText("Nome");

        JLblApelidoBataglin.setText("Apelido");

        JLblCPFBataglin.setText("CPF");

        JLblDataNascBataglin.setText("Data de nascimento");

        JLblNivelBataglin.setText("Nivel");

        JLblSenhaBataglin.setText("Senha");

        jBtnMcbincluir.setBackground(new java.awt.Color(168, 245, 252));
        jBtnMcbincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnMcbincluir.setText("Incluir");
        jBtnMcbincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbincluirActionPerformed(evt);
            }
        });

        jBtnMcbExcluir.setBackground(new java.awt.Color(255, 102, 102));
        jBtnMcbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnMcbExcluir.setText("Excluir");
        jBtnMcbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbExcluirActionPerformed(evt);
            }
        });

        jBtnMcbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnMcbAlterar.setText("Alterar");
        jBtnMcbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbAlterarActionPerformed(evt);
            }
        });

        jBtnMcbCancelar.setBackground(new java.awt.Color(153, 204, 255));
        jBtnMcbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnMcbCancelar.setText("Cancelar");
        jBtnMcbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbCancelarActionPerformed(evt);
            }
        });

        jBtnMcbConfirmar.setBackground(new java.awt.Color(0, 153, 51));
        jBtnMcbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnMcbConfirmar.setText("Confirmar");
        jBtnMcbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbConfirmarActionPerformed(evt);
            }
        });

        jBtnMcbPesquisar.setBackground(new java.awt.Color(51, 153, 255));
        jBtnMcbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnMcbPesquisar.setText("Pesquisar");
        jBtnMcbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbPesquisarActionPerformed(evt);
            }
        });

        jCboMcbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCboMcbAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLblCodigoBataglin)
                            .addComponent(JLblApelidoBataglin)
                            .addComponent(JLblSenhaBataglin)
                            .addComponent(JLblDataNascBataglin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtMcbApelido)
                            .addComponent(jTxtMcbCodigo)
                            .addComponent(jPwfMcbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtMcbData, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtMcbNome)
                                .addGap(224, 224, 224))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblNomeBataglin)
                                    .addComponent(JLblNivelBataglin)
                                    .addComponent(JLblCPFBataglin)
                                    .addComponent(jFmtMcbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboMcbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboMcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnMcbincluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMcbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMcbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMcbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMcbConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMcbPesquisar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblCodigoBataglin)
                    .addComponent(JLblNomeBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMcbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMcbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblApelidoBataglin)
                    .addComponent(JLblCPFBataglin))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtMcbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMcbApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblDataNascBataglin)
                    .addComponent(JLblNivelBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboMcbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtMcbData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblSenhaBataglin)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfMcbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboMcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMcbincluir)
                    .addComponent(jBtnMcbExcluir)
                    .addComponent(jBtnMcbAlterar)
                    .addComponent(jBtnMcbCancelar)
                    .addComponent(jBtnMcbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMcbPesquisar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMcbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbExcluirActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(null, "Tem certeza que deseja continuar? Essa ação não pode ser desfeita",
"Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnMcbExcluirActionPerformed

    private void jBtnMcbincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbincluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnMcbincluirActionPerformed

    private void jBtnMcbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbAlterarActionPerformed
        // TODO add your handling code here:
         habilitar(true);
    }//GEN-LAST:event_jBtnMcbAlterarActionPerformed

    private void jBtnMcbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbCancelarActionPerformed
        // TODO add your handling code here:
         habilitar(false);
    }//GEN-LAST:event_jBtnMcbCancelarActionPerformed

    private void jBtnMcbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnMcbConfirmarActionPerformed

    private void jBtnMcbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbPesquisarActionPerformed
        // TODO add your handling code here:
          JOptionPane.showConfirmDialog(null, "Informe o código de usuário");
    }//GEN-LAST:event_jBtnMcbPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMcbUsuario dialog = new JDlgMcbUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
   
     });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblApelidoBataglin;
    private javax.swing.JLabel JLblCPFBataglin;
    private javax.swing.JLabel JLblCodigoBataglin;
    private javax.swing.JLabel JLblDataNascBataglin;
    private javax.swing.JLabel JLblNivelBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JButton jBtnMcbAlterar;
    private javax.swing.JButton jBtnMcbCancelar;
    private javax.swing.JButton jBtnMcbConfirmar;
    private javax.swing.JButton jBtnMcbExcluir;
    private javax.swing.JButton jBtnMcbPesquisar;
    private javax.swing.JButton jBtnMcbincluir;
    private javax.swing.JComboBox<String> jCboMcbAtivo;
    private javax.swing.JComboBox<String> jCboMcbNivel;
    private javax.swing.JCheckBox jChbAtivoBataglin1;
    private javax.swing.JFormattedTextField jFmtMcbCPF;
    private javax.swing.JFormattedTextField jFmtMcbData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPwfMcbSenha;
    private javax.swing.JTextField jTxtMcbApelido;
    private javax.swing.JTextField jTxtMcbCodigo;
    private javax.swing.JTextField jTxtMcbNome;
    // End of variables declaration//GEN-END:variables
}