/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u07788816108
 */
public class JDlgMcbProduto extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMcbProduto
     */
    public JDlgMcbProduto(java.awt.Frame parent, boolean modal) {
          super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);
        habilitar(false);
    }
    
        public void habilitar(boolean valor) {
        jTxtMcbNome.setEnabled(valor);
        jTxtMcbDescricao.setEnabled(valor);
        jFmtMcbPreco.setEnabled(valor);
        jFmtMcbCodBarras.setEnabled(valor);
        jFmtMcbTipo.setEnabled(valor);
        jFmtMcbCodProduto.setEnabled(valor);
        jCboMcbAtivo.setEnabled(valor);
        jBtnMcbCancelar.setEnabled(valor);
        jBtnMcbConfirmar.setEnabled(valor);
        jBtnMcbIncluir.setEnabled(!valor);
        jBtnMcbAlterar.setEnabled(!valor);
        jBtnMcbExcluir.setEnabled(!valor);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPwfSenhaBataglin = new javax.swing.JPasswordField();
        JLblSenhaBataglin = new javax.swing.JLabel();
        JCboAtivoBataglin = new javax.swing.JComboBox<>();
        JLblAtivoBataglin = new javax.swing.JLabel();
        jChbAtivoBataglin = new javax.swing.JCheckBox();
        jBtnMcbPesquisar = new javax.swing.JButton();
        JLblPrecoBataglin = new javax.swing.JLabel();
        jFmtMcbCodBarras = new javax.swing.JFormattedTextField();
        jBtnMcbIncluir = new javax.swing.JButton();
        jFmtMcbPreco = new javax.swing.JFormattedTextField();
        JLblCodProdutoBataglin = new javax.swing.JLabel();
        jFmtMcbTipo = new javax.swing.JFormattedTextField();
        jBtnMcbExcluir = new javax.swing.JButton();
        jBtnMcbAlterar = new javax.swing.JButton();
        JLblTipoBataglin = new javax.swing.JLabel();
        jBtnMcbCancelar = new javax.swing.JButton();
        jFmtMcbCodProduto = new javax.swing.JFormattedTextField();
        jBtnMcbConfirmar = new javax.swing.JButton();
        JLblNomeBataglin = new javax.swing.JLabel();
        jTxtMcbDescricao = new javax.swing.JTextField();
        JLblCodBarrasBataglin = new javax.swing.JLabel();
        JLblDescricaoBataglin = new javax.swing.JLabel();
        jTxtMcbNome = new javax.swing.JTextField();
        jCboMcbAtivo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jBtnMcbPesquisar1 = new javax.swing.JButton();

        JPwfSenhaBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPwfSenhaBataglinActionPerformed(evt);
            }
        });

        JLblSenhaBataglin.setText("Senha");

        JCboAtivoBataglin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCboAtivoBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCboAtivoBataglinActionPerformed(evt);
            }
        });

        JLblAtivoBataglin.setText("Ativo");

        jChbAtivoBataglin.setText("Ativo");

        jBtnMcbPesquisar.setBackground(new java.awt.Color(51, 153, 255));
        jBtnMcbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnMcbPesquisar.setText("Pesquisar");
        jBtnMcbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbPesquisarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLblPrecoBataglin.setText("Preço");

        jBtnMcbIncluir.setBackground(new java.awt.Color(168, 245, 252));
        jBtnMcbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnMcbIncluir.setText("Incluir");
        jBtnMcbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbIncluirActionPerformed(evt);
            }
        });

        JLblCodProdutoBataglin.setText("Código/Produto");

        jBtnMcbExcluir.setBackground(new java.awt.Color(255, 102, 102));
        jBtnMcbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnMcbExcluir.setText("Excluir");
        jBtnMcbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbExcluirActionPerformed(evt);
            }
        });

        jBtnMcbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnMcbAlterar.setText("Alterar");
        jBtnMcbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbAlterarActionPerformed(evt);
            }
        });

        JLblTipoBataglin.setText("Tipo");

        jBtnMcbCancelar.setBackground(new java.awt.Color(153, 204, 255));
        jBtnMcbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnMcbCancelar.setText("Cancelar");
        jBtnMcbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbCancelarActionPerformed(evt);
            }
        });

        jBtnMcbConfirmar.setBackground(new java.awt.Color(0, 153, 51));
        jBtnMcbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnMcbConfirmar.setText("Confirmar");
        jBtnMcbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbConfirmarActionPerformed(evt);
            }
        });

        JLblNomeBataglin.setText("Nome");

        JLblCodBarrasBataglin.setText("Código de Barras");

        JLblDescricaoBataglin.setText("Descrição");

        jCboMcbAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Ativo");

        jBtnMcbPesquisar1.setBackground(new java.awt.Color(51, 153, 255));
        jBtnMcbPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnMcbPesquisar1.setText("Pesquisar");
        jBtnMcbPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMcbPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblTipoBataglin)
                            .addComponent(JLblNomeBataglin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtMcbCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnMcbIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtMcbNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtMcbTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblCodBarrasBataglin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFmtMcbCodBarras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(JLblDescricaoBataglin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtMcbDescricao, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblPrecoBataglin)
                            .addComponent(jFmtMcbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jBtnMcbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnMcbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnMcbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCboMcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnMcbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnMcbPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(JLblCodProdutoBataglin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblNomeBataglin)
                            .addComponent(JLblDescricaoBataglin)
                            .addComponent(JLblPrecoBataglin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtMcbDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMcbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtMcbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLblCodBarrasBataglin)
                            .addComponent(JLblTipoBataglin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtMcbCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtMcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(JLblCodProdutoBataglin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtMcbCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboMcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMcbIncluir)
                    .addComponent(jBtnMcbExcluir)
                    .addComponent(jBtnMcbAlterar)
                    .addComponent(jBtnMcbCancelar)
                    .addComponent(jBtnMcbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMcbPesquisar1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPwfSenhaBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPwfSenhaBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPwfSenhaBataglinActionPerformed

    private void JCboAtivoBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCboAtivoBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCboAtivoBataglinActionPerformed

    private void jBtnMcbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbIncluirActionPerformed
        // TODO add your handling code here:
         habilitar(true);
    }//GEN-LAST:event_jBtnMcbIncluirActionPerformed

    private void jBtnMcbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbExcluirActionPerformed
        // TODO add your handling code here:
           JOptionPane.showConfirmDialog(null, "Tem certeza que deseja continuar? Essa ação não pode ser desfeita",
"Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnMcbExcluirActionPerformed

    private void jBtnMcbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbAlterarActionPerformed
        // TODO add your handling code here:
           habilitar(true);
    }//GEN-LAST:event_jBtnMcbAlterarActionPerformed

    private void jBtnMcbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbCancelarActionPerformed
        // TODO add your handling code here:
          habilitar(false);
    }//GEN-LAST:event_jBtnMcbCancelarActionPerformed

    private void jBtnMcbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnMcbConfirmarActionPerformed

    private void jBtnMcbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Informe o código de produto");
    }//GEN-LAST:event_jBtnMcbPesquisarActionPerformed

    private void jBtnMcbPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMcbPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnMcbPesquisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMcbProduto dialog = new JDlgMcbProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCboAtivoBataglin;
    private javax.swing.JLabel JLblAtivoBataglin;
    private javax.swing.JLabel JLblCodBarrasBataglin;
    private javax.swing.JLabel JLblCodProdutoBataglin;
    private javax.swing.JLabel JLblDescricaoBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblPrecoBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JLabel JLblTipoBataglin;
    private javax.swing.JPasswordField JPwfSenhaBataglin;
    private javax.swing.JButton jBtnMcbAlterar;
    private javax.swing.JButton jBtnMcbCancelar;
    private javax.swing.JButton jBtnMcbConfirmar;
    private javax.swing.JButton jBtnMcbExcluir;
    private javax.swing.JButton jBtnMcbIncluir;
    private javax.swing.JButton jBtnMcbPesquisar;
    private javax.swing.JButton jBtnMcbPesquisar1;
    private javax.swing.JComboBox<String> jCboMcbAtivo;
    private javax.swing.JCheckBox jChbAtivoBataglin;
    private javax.swing.JFormattedTextField jFmtMcbCodBarras;
    private javax.swing.JFormattedTextField jFmtMcbCodProduto;
    private javax.swing.JFormattedTextField jFmtMcbPreco;
    private javax.swing.JFormattedTextField jFmtMcbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtMcbDescricao;
    private javax.swing.JTextField jTxtMcbNome;
    // End of variables declaration//GEN-END:variables
}
