/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 *
 * @author u07788816108
 */
public class JDlgMcbCliente extends javax.swing.JDialog {

    /**
     * Creates new form JDlgMcbCliente
     */
       public JDlgMcbCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setLocationRelativeTo(null);
        habilitar(false);
    }

        public void habilitar(boolean valor) {
        jTxtNomeBataglin.setEnabled(valor);
        jFmtCPFBataglin.setEnabled(valor);
        jTxtSexoBataglin.setEnabled(valor);
        jFmtDataNascBataglin.setEnabled(valor);
        jChbAtivoBataglin1.setEnabled(valor);
        jTxtCodigoBataglin.setEnabled(valor);
        jPwfSenhaBataglin.setEnabled(valor);
        jFmtRGBataglin.setEnabled(valor);
        jFmtCEPBataglin.setEnabled(valor);
        jTxtBairroBataglin.setEnabled(valor);
        jTxtCidadeBataglin.setEnabled(valor);
        jTxtEstadoBataglin.setEnabled(valor);
        jFmtNumeroBataglin.setEnabled(valor);
        jBtnCancelarBataglin.setEnabled(valor);
        jBtnConfirmarBataglin.setEnabled(valor);
        jBtnIncluirBataglin.setEnabled(!valor);
        jBtnAlterarBataglin.setEnabled(!valor);
        jBtnExcluirBataglin.setEnabled(!valor);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        JCboAtivoBataglin = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        JLblNomeBataglin = new javax.swing.JLabel();
        JLblCEPBataglin = new javax.swing.JLabel();
        JLblCidadeBataglin = new javax.swing.JLabel();
        JLblBairroBataglin = new javax.swing.JLabel();
        JLblRGBataglin = new javax.swing.JLabel();
        JLblEmailBataglin = new javax.swing.JLabel();
        JLblTelefoneBataglin = new javax.swing.JLabel();
        JLblEstadoBataglin = new javax.swing.JLabel();
        JLblRuaBataglin = new javax.swing.JLabel();
        JLblDataNascBataglin = new javax.swing.JLabel();
        JLblSexoBataglin = new javax.swing.JLabel();
        JLblSenhaBataglin = new javax.swing.JLabel();
        jTxtNomeBataglin = new javax.swing.JTextField();
        jTxtEmailBataglin = new javax.swing.JTextField();
        jTxtBairroBataglin = new javax.swing.JTextField();
        jTxtCidadeBataglin = new javax.swing.JTextField();
        jTxtEstadoBataglin = new javax.swing.JTextField();
        JLblCPFBataglin = new javax.swing.JLabel();
        JLblEnderecoBataglin = new javax.swing.JLabel();
        jTxtRuaBataglin = new javax.swing.JTextField();
        jFmtNumeroBataglin = new javax.swing.JFormattedTextField();
        jFmtCEPBataglin = new javax.swing.JFormattedTextField();
        jFmtCPFBataglin = new javax.swing.JFormattedTextField();
        jFmtRGBataglin = new javax.swing.JFormattedTextField();
        jFmtDataNascBataglin = new javax.swing.JFormattedTextField();
        jTxtSexoBataglin = new javax.swing.JTextField();
        jFmtTelefoneBataglin = new javax.swing.JFormattedTextField();
        jPwfSenhaBataglin = new javax.swing.JPasswordField();
        jBtnIncluirBataglin = new javax.swing.JButton();
        jBtnExcluirBataglin = new javax.swing.JButton();
        jBtnAlterarBataglin = new javax.swing.JButton();
        jBtnCancelarBataglin = new javax.swing.JButton();
        jBtnConfirmarBataglin = new javax.swing.JButton();
        JLblCodigoBataglin = new javax.swing.JLabel();
        jTxtCodigoBataglin = new javax.swing.JTextField();
        jChbAtivoBataglin1 = new javax.swing.JCheckBox();

        jFormattedTextField1.setText("jFormattedTextField1");

        jLabel2.setText("jLabel2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jLabel14.setText("jLabel14");

        JCboAtivoBataglin.setText("Ativo");
        JCboAtivoBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCboAtivoBataglinActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        JLblNomeBataglin.setText("Nome");

        JLblCEPBataglin.setText("CEP");

        JLblCidadeBataglin.setText("Cidade");

        JLblBairroBataglin.setText("Bairro");

        JLblRGBataglin.setText("RG");

        JLblEmailBataglin.setText("Email");

        JLblTelefoneBataglin.setText("Telefone");

        JLblEstadoBataglin.setText("Estado");

        JLblRuaBataglin.setText("Rua");

        JLblDataNascBataglin.setText("Data de Nascimento");

        JLblSexoBataglin.setText("Sexo");

        JLblSenhaBataglin.setText("Senha");

        jTxtNomeBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeBataglinActionPerformed(evt);
            }
        });

        jTxtBairroBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBairroBataglinActionPerformed(evt);
            }
        });

        jTxtCidadeBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCidadeBataglinActionPerformed(evt);
            }
        });

        JLblCPFBataglin.setText("CPF");

        JLblEnderecoBataglin.setText("Número");

        jFmtNumeroBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtNumeroBataglinActionPerformed(evt);
            }
        });

        jBtnIncluirBataglin.setBackground(new java.awt.Color(168, 245, 252));
        jBtnIncluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluirBataglin.setText("Incluir");

        jBtnExcluirBataglin.setBackground(new java.awt.Color(255, 102, 102));
        jBtnExcluirBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluirBataglin.setText("Excluir");

        jBtnAlterarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterarBataglin.setText("Alterar");

        jBtnCancelarBataglin.setBackground(new java.awt.Color(153, 204, 255));
        jBtnCancelarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelarBataglin.setText("Cancelar");
        jBtnCancelarBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarBataglinActionPerformed(evt);
            }
        });

        jBtnConfirmarBataglin.setBackground(new java.awt.Color(0, 153, 51));
        jBtnConfirmarBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmarBataglin.setText("Confirmar");

        JLblCodigoBataglin.setText("Código");

        jChbAtivoBataglin1.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLblNomeBataglin)
                            .addComponent(JLblCEPBataglin)
                            .addComponent(JLblCPFBataglin)
                            .addComponent(jFmtCEPBataglin, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jFmtCPFBataglin)
                            .addComponent(jTxtNomeBataglin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtEmailBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblEmailBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblTelefoneBataglin)
                                    .addComponent(jFmtTelefoneBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtRGBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblRGBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblDataNascBataglin)
                                    .addComponent(jFmtDataNascBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLblSexoBataglin)
                                    .addComponent(jTxtSexoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtEstadoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLblBairroBataglin)
                                            .addComponent(jTxtBairroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(JLblEstadoBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtCidadeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtRuaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JLblRuaBataglin)))
                                    .addComponent(JLblCidadeBataglin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtNumeroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLblEnderecoBataglin))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnIncluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBtnExcluirBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBtnAlterarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBtnCancelarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(JLblCodigoBataglin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JLblSenhaBataglin)
                                    .addGap(256, 256, 256)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jTxtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChbAtivoBataglin1)
                            .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblNomeBataglin)
                    .addComponent(JLblEmailBataglin)
                    .addComponent(JLblTelefoneBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNomeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmailBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtTelefoneBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLblCPFBataglin)
                        .addComponent(JLblRGBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLblDataNascBataglin)
                        .addComponent(JLblSexoBataglin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSexoBataglin)
                    .addComponent(jFmtDataNascBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtRGBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCPFBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblCEPBataglin)
                    .addComponent(JLblEstadoBataglin)
                    .addComponent(JLblBairroBataglin)
                    .addComponent(JLblCidadeBataglin)
                    .addComponent(JLblRuaBataglin)
                    .addComponent(JLblEnderecoBataglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCEPBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEstadoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBairroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCidadeBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRuaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtNumeroBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLblSenhaBataglin)
                    .addComponent(JLblCodigoBataglin))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenhaBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCodigoBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivoBataglin1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluirBataglin)
                    .addComponent(jBtnExcluirBataglin)
                    .addComponent(jBtnAlterarBataglin)
                    .addComponent(jBtnCancelarBataglin)
                    .addComponent(jBtnConfirmarBataglin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeBataglinActionPerformed

    private void jTxtCidadeBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCidadeBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCidadeBataglinActionPerformed

    private void jTxtBairroBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBairroBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBairroBataglinActionPerformed

    private void JCboAtivoBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCboAtivoBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCboAtivoBataglinActionPerformed

    private void jFmtNumeroBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtNumeroBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtNumeroBataglinActionPerformed

    private void jBtnCancelarBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarBataglinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarBataglinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMcbCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMcbCliente dialog = new JDlgMcbCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCboAtivoBataglin;
    private javax.swing.JLabel JLblBairroBataglin;
    private javax.swing.JLabel JLblCEPBataglin;
    private javax.swing.JLabel JLblCPFBataglin;
    private javax.swing.JLabel JLblCidadeBataglin;
    private javax.swing.JLabel JLblCodigoBataglin;
    private javax.swing.JLabel JLblDataNascBataglin;
    private javax.swing.JLabel JLblEmailBataglin;
    private javax.swing.JLabel JLblEnderecoBataglin;
    private javax.swing.JLabel JLblEstadoBataglin;
    private javax.swing.JLabel JLblNomeBataglin;
    private javax.swing.JLabel JLblRGBataglin;
    private javax.swing.JLabel JLblRuaBataglin;
    private javax.swing.JLabel JLblSenhaBataglin;
    private javax.swing.JLabel JLblSexoBataglin;
    private javax.swing.JLabel JLblTelefoneBataglin;
    private javax.swing.JButton jBtnAlterarBataglin;
    private javax.swing.JButton jBtnCancelarBataglin;
    private javax.swing.JButton jBtnConfirmarBataglin;
    private javax.swing.JButton jBtnExcluirBataglin;
    private javax.swing.JButton jBtnIncluirBataglin;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jChbAtivoBataglin1;
    private javax.swing.JFormattedTextField jFmtCEPBataglin;
    private javax.swing.JFormattedTextField jFmtCPFBataglin;
    private javax.swing.JFormattedTextField jFmtDataNascBataglin;
    private javax.swing.JFormattedTextField jFmtNumeroBataglin;
    private javax.swing.JFormattedTextField jFmtRGBataglin;
    private javax.swing.JFormattedTextField jFmtTelefoneBataglin;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPwfSenhaBataglin;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTxtBairroBataglin;
    private javax.swing.JTextField jTxtCidadeBataglin;
    private javax.swing.JTextField jTxtCodigoBataglin;
    private javax.swing.JTextField jTxtEmailBataglin;
    private javax.swing.JTextField jTxtEstadoBataglin;
    private javax.swing.JTextField jTxtNomeBataglin;
    private javax.swing.JTextField jTxtRuaBataglin;
    private javax.swing.JTextField jTxtSexoBataglin;
    // End of variables declaration//GEN-END:variables
}
