/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author u07788816108
 */
public class JFrmBataglin extends javax.swing.JFrame {

    /**
     * Creates new form JFrmBataglin
     */
    public JFrmBataglin() {
        initComponents();
        setTitle("Material Escolar da Mika");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMnuMcbMenu = new javax.swing.JMenuBar();
        JMnuMcbCadastro = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuMcbUsuario = new javax.swing.JMenuItem();
        jMnuMcbFornecedor = new javax.swing.JMenuItem();
        jMnuMcbCliente = new javax.swing.JMenuItem();
        jMnuMcbVendedor = new javax.swing.JMenuItem();
        jMnuMcbProduto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMnuMcbSair = new javax.swing.JMenuItem();
        jMnuMcbMovimento = new javax.swing.JMenu();
        jMnuMcbCompras = new javax.swing.JMenuItem();
        jMnuMcbVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JMnuMcbCadastro.setBackground(new java.awt.Color(153, 204, 255));
        JMnuMcbCadastro.setText("Cadastro");
        JMnuMcbCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuMcbCadastroActionPerformed(evt);
            }
        });
        JMnuMcbCadastro.add(jSeparator1);

        jMnuMcbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuMcbUsuario.setText("Usuários");
        jMnuMcbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMcbUsuarioActionPerformed(evt);
            }
        });
        JMnuMcbCadastro.add(jMnuMcbUsuario);

        jMnuMcbFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jMnuMcbFornecedor.setText("Fornecedor");
        jMnuMcbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMcbFornecedorActionPerformed(evt);
            }
        });
        JMnuMcbCadastro.add(jMnuMcbFornecedor);

        jMnuMcbCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuMcbCliente.setText("Cliente");
        jMnuMcbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMcbClienteActionPerformed(evt);
            }
        });
        JMnuMcbCadastro.add(jMnuMcbCliente);

        jMnuMcbVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMnuMcbVendedor.setText("Vendedor");
        jMnuMcbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMcbVendedorActionPerformed(evt);
            }
        });
        JMnuMcbCadastro.add(jMnuMcbVendedor);

        jMnuMcbProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jMnuMcbProduto.setText("Produto");
        jMnuMcbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMcbProdutoActionPerformed(evt);
            }
        });
        JMnuMcbCadastro.add(jMnuMcbProduto);
        JMnuMcbCadastro.add(jSeparator2);

        jMnuMcbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuMcbSair.setText("Sair");
        JMnuMcbCadastro.add(jMnuMcbSair);

        JMnuMcbMenu.add(JMnuMcbCadastro);

        jMnuMcbMovimento.setText("Movimento");

        jMnuMcbCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/comprasproduto.png"))); // NOI18N
        jMnuMcbCompras.setText("Compras");
        jMnuMcbCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMcbComprasActionPerformed(evt);
            }
        });
        jMnuMcbMovimento.add(jMnuMcbCompras);

        jMnuMcbVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas_produto.png"))); // NOI18N
        jMnuMcbVendas.setText("Vendas");
        jMnuMcbMovimento.add(jMnuMcbVendas);

        JMnuMcbMenu.add(jMnuMcbMovimento);

        setJMenuBar(JMnuMcbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMnuMcbCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuMcbCadastroActionPerformed
        // TODO add your handling code here:
         System.exit(0); 
    }//GEN-LAST:event_JMnuMcbCadastroActionPerformed

    private void jMnuMcbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMcbUsuarioActionPerformed
        // TODO add your handling code here:
         JDlgMcbUsuario jDlgMcbUsuario = new JDlgMcbUsuario(null, true);
       jDlgMcbUsuario.setVisible(true);
    }//GEN-LAST:event_jMnuMcbUsuarioActionPerformed

    private void jMnuMcbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMcbVendedorActionPerformed
        // TODO add your handling code here:
          JDlgMcbVendedor jDlgMcbVendedor = new JDlgMcbVendedor(null, true);
       jDlgMcbVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuMcbVendedorActionPerformed

    private void jMnuMcbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMcbClienteActionPerformed
        // TODO add your handling code here:
          JDlgMcbCliente jDlgMcbCliente = new JDlgMcbCliente(null, true);
       jDlgMcbCliente.setVisible(true);
    }//GEN-LAST:event_jMnuMcbClienteActionPerformed

    private void jMnuMcbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMcbFornecedorActionPerformed
        // TODO add your handling code here:
          JDlgFornecedor jDlgFornecedor = new JDlgFornecedor(null, true);
       jDlgFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuMcbFornecedorActionPerformed

    private void jMnuMcbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMcbProdutoActionPerformed
        // TODO add your handling code here:
          JDlgMcbProduto jDlgMcbProduto = new JDlgMcbProduto(null, true);
       jDlgMcbProduto.setVisible(true);
    }//GEN-LAST:event_jMnuMcbProdutoActionPerformed

    private void jMnuMcbComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMcbComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuMcbComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmBataglin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmBataglin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmBataglin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmBataglin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmBataglin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMnuMcbCadastro;
    private javax.swing.JMenuBar JMnuMcbMenu;
    private javax.swing.JMenuItem jMnuMcbCliente;
    private javax.swing.JMenuItem jMnuMcbCompras;
    private javax.swing.JMenuItem jMnuMcbFornecedor;
    private javax.swing.JMenu jMnuMcbMovimento;
    private javax.swing.JMenuItem jMnuMcbProduto;
    private javax.swing.JMenuItem jMnuMcbSair;
    private javax.swing.JMenuItem jMnuMcbUsuario;
    private javax.swing.JMenuItem jMnuMcbVendas;
    private javax.swing.JMenuItem jMnuMcbVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
