/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author u07788816108
 */
public class JFrmBataglin extends javax.swing.JFrame {

    /**
     * Creates new form JFrmBataglin
     */
    public JFrmBataglin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMnuMenuBataglin = new javax.swing.JMenuBar();
        JMnuCadastroBataglin = new javax.swing.JMenu();
        JChbUsuarioBataglin = new javax.swing.JCheckBoxMenuItem();
        JChbClienteBataglin = new javax.swing.JCheckBoxMenuItem();
        JChbFornecedorBataglin = new javax.swing.JCheckBoxMenuItem();
        JChbProdutoBataglin = new javax.swing.JCheckBoxMenuItem();
        JChbVendedorBataglin = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JChbSairBataglin = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JChbComprasBataglin = new javax.swing.JCheckBoxMenuItem();
        JChbVendasBataglin = new javax.swing.JCheckBoxMenuItem();
        JChbCompras_ProdutosBataglin = new javax.swing.JCheckBoxMenuItem();
        JChbVendas_ProdutoBataglin = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JMnuCadastroBataglin.setBackground(new java.awt.Color(153, 204, 255));
        JMnuCadastroBataglin.setText("Cadastro");
        JMnuCadastroBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuCadastroBataglinActionPerformed(evt);
            }
        });

        JChbUsuarioBataglin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JChbUsuarioBataglin.setSelected(true);
        JChbUsuarioBataglin.setText("Usuário");
        JChbUsuarioBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        JChbUsuarioBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JChbUsuarioBataglinActionPerformed(evt);
            }
        });
        JMnuCadastroBataglin.add(JChbUsuarioBataglin);

        JChbClienteBataglin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JChbClienteBataglin.setSelected(true);
        JChbClienteBataglin.setText("Cliente");
        JChbClienteBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        JChbClienteBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JChbClienteBataglinActionPerformed(evt);
            }
        });
        JMnuCadastroBataglin.add(JChbClienteBataglin);

        JChbFornecedorBataglin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JChbFornecedorBataglin.setSelected(true);
        JChbFornecedorBataglin.setText("Fornecedor");
        JChbFornecedorBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        JChbFornecedorBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JChbFornecedorBataglinActionPerformed(evt);
            }
        });
        JMnuCadastroBataglin.add(JChbFornecedorBataglin);

        JChbProdutoBataglin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JChbProdutoBataglin.setSelected(true);
        JChbProdutoBataglin.setText("Produto");
        JChbProdutoBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Caderno espiral glossy de capa azul.png"))); // NOI18N
        JChbProdutoBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JChbProdutoBataglinActionPerformed(evt);
            }
        });
        JMnuCadastroBataglin.add(JChbProdutoBataglin);

        JChbVendedorBataglin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JChbVendedorBataglin.setSelected(true);
        JChbVendedorBataglin.setText("Vendedor");
        JChbVendedorBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/categoria.png"))); // NOI18N
        JChbVendedorBataglin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JChbVendedorBataglinActionPerformed(evt);
            }
        });
        JMnuCadastroBataglin.add(JChbVendedorBataglin);
        JMnuCadastroBataglin.add(jSeparator1);

        JChbSairBataglin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JChbSairBataglin.setSelected(true);
        JChbSairBataglin.setText("Sair");
        JChbSairBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        JMnuCadastroBataglin.add(JChbSairBataglin);

        JMnuMenuBataglin.add(JMnuCadastroBataglin);

        jMenu2.setText("Movimento");

        JChbComprasBataglin.setSelected(true);
        JChbComprasBataglin.setText("Compras");
        JChbComprasBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jMenu2.add(JChbComprasBataglin);

        JChbVendasBataglin.setSelected(true);
        JChbVendasBataglin.setText("Vendas");
        JChbVendasBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMenu2.add(JChbVendasBataglin);

        JChbCompras_ProdutosBataglin.setSelected(true);
        JChbCompras_ProdutosBataglin.setText("Compras_Produto");
        JChbCompras_ProdutosBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/comprasproduto.png"))); // NOI18N
        jMenu2.add(JChbCompras_ProdutosBataglin);

        JChbVendas_ProdutoBataglin.setSelected(true);
        JChbVendas_ProdutoBataglin.setText("Vendas_Produto");
        JChbVendas_ProdutoBataglin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas_produto.png"))); // NOI18N
        jMenu2.add(JChbVendas_ProdutoBataglin);

        JMnuMenuBataglin.add(jMenu2);

        setJMenuBar(JMnuMenuBataglin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMnuCadastroBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuCadastroBataglinActionPerformed
        // TODO add your handling code here:
           
        
    }//GEN-LAST:event_JMnuCadastroBataglinActionPerformed

    private void JChbUsuarioBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JChbUsuarioBataglinActionPerformed
        JDlgMcbUsuario jDlgMcbUsuario = new JDlgMcbUsuario(null, true);
        jDlgMcbUsuario.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_JChbUsuarioBataglinActionPerformed

    private void JChbClienteBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JChbClienteBataglinActionPerformed
        // TODO add your handling code here:
          JDlgMcbCliente jDlgMcbCliente = new JDlgMcbCliente(null, true);
        jDlgMcbCliente.setVisible(true);
    }//GEN-LAST:event_JChbClienteBataglinActionPerformed

    private void JChbFornecedorBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JChbFornecedorBataglinActionPerformed
        // TODO add your handling code here:
        JDlgFornecedor jDlgFornecedor = new JDlgFornecedor(null, true);
        jDlgFornecedor.setVisible(true);
        //Descobri agora que não coloquei Mcb no fornecedor.
    }//GEN-LAST:event_JChbFornecedorBataglinActionPerformed

    private void JChbProdutoBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JChbProdutoBataglinActionPerformed
        // TODO add your handling code here:
           JDlgMcbProduto jDlgMcbProduto = new JDlgMcbProduto(null, true);
        jDlgMcbProduto.setVisible(true);
    }//GEN-LAST:event_JChbProdutoBataglinActionPerformed

    private void JChbVendedorBataglinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JChbVendedorBataglinActionPerformed
        // TODO add your handling code here:
          JDlgMcbVendedor jDlgMcbVendedor = new JDlgMcbVendedor(null, true);
        jDlgMcbVendedor.setVisible(true);
        
    }//GEN-LAST:event_JChbVendedorBataglinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmBataglin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmBataglin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmBataglin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmBataglin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmBataglin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem JChbClienteBataglin;
    private javax.swing.JCheckBoxMenuItem JChbComprasBataglin;
    private javax.swing.JCheckBoxMenuItem JChbCompras_ProdutosBataglin;
    private javax.swing.JCheckBoxMenuItem JChbFornecedorBataglin;
    private javax.swing.JCheckBoxMenuItem JChbProdutoBataglin;
    private javax.swing.JCheckBoxMenuItem JChbSairBataglin;
    private javax.swing.JCheckBoxMenuItem JChbUsuarioBataglin;
    private javax.swing.JCheckBoxMenuItem JChbVendasBataglin;
    private javax.swing.JCheckBoxMenuItem JChbVendas_ProdutoBataglin;
    private javax.swing.JCheckBoxMenuItem JChbVendedorBataglin;
    private javax.swing.JMenu JMnuCadastroBataglin;
    private javax.swing.JMenuBar JMnuMenuBataglin;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
